### ISSUE TITLE
No CSS in HTML output with interactive=FALSE

### ISSUE THREAD

**Issue by chambm** [brodieG/diffobj#102]
`diffobj::diffPrint("ABC\nDEF", "ABC\nXYZ", interactive=FALSE, mode="unified", format="html")`

I just get plain HTML:

`<div class='diffobj_container light rgb'><pre><div class='row'><div class='line banner'><div class='delete'><div class='gutter'><div class='delete'>&lt;</div><div class='pad'> </div></div><div class='text'><div class='delete'><span class='word delete'>"ABC\nDEF"</span></div></div></div></div></div><div class='row'><div class='line banner'><div class='insert'><div class='gutter'><div class='insert'>&gt;</div><div class='pad'> </div></div><div class='text'><div class='insert'><span class='word insert'>"ABC\nXYZ"</span></div></div></div></div></div><div class='row'><div class='line'><div class='header'>@@ 1 / 1 @@</div></div></div><div class='row'><div class='line'><div class='delete'><div class='gutter'><div class='delete'>&lt;</div><div class='pad'> </div></div><div class='text'><div class='delete'><span class='trim'>[1] </span><span class='word delete'>"ABC\nDEF"</span><span class='trim'></span></div></div></div></div></div><div class='row'><div class='line'><div class='insert'><div cl... <truncated>
`

I have to say I find the "styles" part of the documentation pretty daunting. I assume it's just supposed to work similarly between interactive TRUE/FALSE. :)

```
Session info -------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.3 (2017-03-06)
 system   x86_64, mingw32             
 ui       RStudio (1.0.136)           
 language (EN)                        
 collate  English_United States.1252  
 tz       America/Chicago             
 date     2017-04-18                  

Packages -----------------------------------------------------------------------------------------------------------------------------------------------------------
 package       * version  date       source        
 BiocGenerics  * 0.20.0   2016-10-18 Bioconductor  
 bitops          1.0-6    2013-08-17 CRAN (R 3.3.2)
 crayon          1.3.2    2016-06-28 CRAN (R 3.3.3)
 devtools        1.12.0   2016-06-24 CRAN (R 3.3.3)
 diffobj         0.1.6    2016-11-15 CRAN (R 3.3.3)
 digest          0.6.12   2017-01-27 CRAN (R 3.3.3)
 GenomeInfoDb  * 1.10.3   2017-02-07 Bioconductor  
 GenomicRanges * 1.26.4   2017-03-18 Bioconductor  
 IRanges       * 2.8.2    2017-03-18 Bioconductor  
 memoise         1.0.0    2016-01-29 CRAN (R 3.3.2)
 RCurl           1.95-4.8 2016-03-01 CRAN (R 3.3.2)
 S4Vectors     * 0.12.2   2017-03-18 Bioconductor  
 withr           1.0.2    2016-06-20 CRAN (R 3.3.2)
 XVector         0.14.1   2017-03-18 Bioconductor  
 zlibbioc        1.20.0   2016-10-18 Bioconductor 
```

**Comment by brodieG** [comment]
I'll admit it took me a non-trivial amount of time to figure out from the docs how to do this:
```
diffobj::diffPrint(
  "ABC\nDEF", "ABC\nXYZ", interactive=FALSE, mode="unified", format="html",
  style=list(html.output='diff.w.style')
)
```
but at least I didn't have too look at the source...  I think this resolves the issue, but I'll leave it as open as a reminder to either add more examples or try to tackle the docs again.

**Comment by brodieG** [comment]
Also, what are you trying to achieve with `interactive=FALSE`?  Do you just want to prevent the launching of a browser window, but otherwise get the HTML?  If so you should use:
```
as.character(diffobj::diffPrint("ABC\nDEF", "ABC\nXYZ", mode="unified", format="html"))
```
That will render the same way as it normally does, but instead of trying to spawn a browser window, it will just return the HTML.

**Comment by chambm** [comment]
Nice, I'll try that. I'm trying to use it in potentially non-interactive testing, so I figured always using interactive=FALSE would be safer. So even if interactive() returns false, the as.character() will return with color??

**Comment by brodieG** [comment]
Ah, I see.  No, it that case you'll have to fully specify the parameters.  If you are doing this for a lot of tests, and want to get the same result whether running interactively or not, you may want to set:
```
old.opts <- options(diffobj.interactive=FALSE, diffobj.mode='unified', diffobj.format='html', diffobj.style=list(html.output='diff.w.style`))
# test code
options(old.opt)
```
in your test files.

**Comment by brodieG** [comment]
Your specific issue is considered "fixed" via making the documentation for `Styles` slightly more daunting (See #104).  That said, I _might_ ultimately change the behavior to make it consistent between interactive vs. non, but I am on the fence on that one (see #103).
