### ISSUE TITLE
Rendering diff in rmarkdown?

### ISSUE THREAD

**Issue by JBGruber** [brodieG/diffobj#120]
Thank you @brodieG for this package, I really appreciate you took the time to solve the problem of comparing texts directly in R for the community!

I wondered though if it is possible to display the styled output from `diffPrint()` in an rmarkdown report. I would like to visualise the differences between a few texts and like the style `diffPrint()` uses. This is what I've got so far and I hoped you could give me a pointer on how to accomplish this. 

``` r
duplicates <- data.frame(text_original = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas laoreet risus et eros sagittis aliquam. Donec fringilla pharetra vestibulum. Fusce vestibulum imperdiet nibh ac rutrum. Aenean sollicitudin, tellus sed tempor varius, quam dolor ornare sapien, eu faucibus quam arcu vestibulum velit. Praesent maximus odio magna, in vulputate arcu cursus vitae. Praesent condimentum purus sit amet nisl vestibulum semper. Nunc quis eros ultricies, elementum eros sed, ullamcorper nunc. Nunc dictum commodo quam, et venenatis velit porta sit amet. Nunc et lorem et odio scelerisque vulputate sed at purus. Sed velit ipsum, consequat vel tristique tincidunt, semper in odio. Nullam pharetra laoreet velit quis sollicitudin. Fusce tellus felis, scelerisque id ipsum et, varius iaculis erat. Sed porttitor at quam sed rhoncus. Donec rutrum justo nec malesuada aliquam. Maecenas feugiat odio ac ante consequat, aliquet tempus magna tempus. Morbi convallis orci felis, ac ultricies ex dignissim in. Donec ornare vehicula ante eu interdum.",
                         text_duplicate = "Lorem dolor sit amet, consectetur elit. Maecenas laoreet risus et eros sagittis aliquam. Donec fringilla pharetra vestibulum. Fusce vestibulum imperdiet nibh ac rutrum. Aenean sollicitudin, tellus sed tempor varius, quam dolor ornare sapien, eu faucibus quam arcu vestibulum velit. Praesent maximus odio magna, in vulputate arcu cursus vitae. Praesent condimentum purus sit amet nisl vestibulum semper. Nunc quis eros ultricies, elementum sed, ullamcorper nunc. Nunc commodo quam, et venenatis velit porta sit amet. Nunc et lorem et odio scelerisque vulputate sed at purus. Sed velit ipsum, consequat vel tristique tincidunt, semper in odio. Nullam pharetra laoreet velit quis sollicitudin. Fusce tellus felis, scelerisque id ipsum et, varius iaculis erat. Sed porttitor at quam sed rhoncus. Donec rutrum justo nec malesuada aliquam. Maecenas feugiat odio ac ante consequat, aliquet tempus magna tempus. Morbi convallis orci felis, ac ultricies ex dignissim in. Donec ornare vehicula ante eu interdum.",
                         stringsAsFactors = FALSE)

library(diffobj)
for (i in 1) {
  orig <- unname(unlist(quanteda::tokens(duplicates$text_original[i], what = "sentence")))
  dup <- unname(unlist(quanteda::tokens(duplicates$text_duplicate[i], what = "sentence")))
  diff <- diffPrint(current = orig,
                    target = dup,
                    format = "html",
                    interactive = FALSE)
  print(diff)
}
```

The desired output would be html and I use more than one iteration in the loop usually. The `quanteda` part is just to split up the otherwise unstructured text into sentences. I already asked the question on [SO](https://stackoverflow.com/questions/51113374/visualise-diff-in-html-report) but didn't get a reply.

Thanks

**Comment by brodieG** [comment]
@JBGruber you can absolutely do this, but it takes a little doing.  Here is an [example on a vignette](http://htmlpreview.github.io/?https://github.com/brodieG/ggbg/blob/vignette/inst/doc/extensions.html#facetmap_data) I'm working on ATM.

The key bits are:

```
options(
  digits=2, diffobj.pager="off", crayon.enabled=TRUE,
  # diffobj.format="ansi256", diffobj.brightness="light",
  diffobj.format="html", diffobj.disp.width=120,
  diffobj.ignore.white.space=TRUE
)
```
and then using the `results="asis"` knit chunk option.  You can look at the source of the vignette to see how it is done.  Let me know if you have trouble getting it to work.

**Comment by tcgriffith** [comment]
I got it working after some tweaks. 
[here is the result](https://tcgriffith.github.io/cosx_exps/test29.html)
[here is the rmd source](https://raw.githubusercontent.com/tcgriffith/cosx_exps/master/test29.Rmd)

Following @brodieG 's instruction, I found that the output of diffPrint doesn't contain css to format the output, so I manually copy& pasted the css style and it worked. It's also possible to separate css into an individual file and include it in the YAML header.

**Comment by brodieG** [comment]
Thanks @tcgriffith, I was just thinking that I had forgotten to mention the CSS bit, but you beat me to it.  This is what I use in the yaml bit:
```
output:
    rmarkdown::html_vignette:
        toc: true
        css:
          - !expr file.path(system.file(package="diffobj"),"css","diffobj.css")
          - styles.css
```

**Comment by JBGruber** [comment]
Thanks a lot @tcgriffith  and @brodieG ! I tried to render the vignette yesterday but got `Could not fetch styles.css` and it was too late where I am to go looking for the file. 

I like your solution @tcgriffith  with including the css in the .rmd directly and will go ahead with it.

The solution might not be ideal in the long run since knitting to pdf etc. does not work. But I see now that `diffobj` produces html code which would need to be translated to Latex first to work in a PDF. So for the moment, I'm perfectly happy with this solution!

**Comment by JBGruber** [comment]
Thanks again for your help. I wanted to let you know that I included a convenience wrapper for the `diffPrint` function in my [own package](https://github.com/JBGruber/LexisNexisTools) now and solved the issue with an option named `output_html`, so that the user can decide whether the outputted html is formatted for markdown or is rendered in the browser. The css file is loaded after the output of `diffPrint` via:

```
if (output_html) {
    cat("<style>", readLines(system.file("css", "diffobj.css", package = "diffobj")),
        "</style>")
 }
```
I think it's a very helpful addition to my package and I'm truly grateful you took the time to write `diffobj` :smiley:!
