### ISSUE TITLE
diffobj and lumberjack

### ISSUE THREAD

**Issue by markvanderloo** [brodieG/diffobj#122]
Hi Brodie,

Your package makes awesome comparisons between objects. I have a package called [lumberjack](https://CRAN.R-project.org/package=lumberjack) that allows you to log changes in objects or data as they flow through a not-a-pipe operator. I think that the diffs that your package make would be a very nice way of logging. We could store consecutive diffs so people can visualize changes in the cli.

The `lumberjack` framework is extensible and anyone can define loggers, by providing an `R6` or `RC` object. The idea is that any packages that compare R objects can `Enhance` the lumberjack package by providing a logger object. This way, no installation dependencies are needed and everyone stays [lightweight](http://www.tinyverse.org/).

I think it would be interesting and useful to have a `lumberjack` logger object in `diffobj`. If you are open to it, I can do a PR. I would basically add one file to the R directory and one to the test directory. I could do it in `R6` or `RC`, as you wish (you already import `methods` so `RC` may be your preference). I would also add an `Enhances` line to your `DESCRIPTION`. 

More information:

- [Introductory vignette](https://cran.r-project.org/web/packages/lumberjack/vignettes/intro.html) and [how to add loggers](https://cran.r-project.org/web/packages/lumberjack/vignettes/extending.html)
- [My talk](https://www.youtube.com/watch?v=DNZs0CHBU4s&t=171s) at eRum2018

Also:
- The [daff](https://cran.r-project.org/web/packages/daff/index.html) package will also feature a lumberjack logger on its next release.
- lumberjack 0.3.0 coming soon.

Cheers,
Mark

**Comment by brodieG** [comment]
Let me look at it and I'll get back to you.

**Comment by brodieG** [comment]
Just looked a little at this.  Is it fair to say that "Enhances" is not needed other than for lookup convenience on the CRAN pages?  Seems like there is nothing in the sample log objects that is lumberjack specific (other than the generic API).

Also, what is the purpose of the test file you wish to add?  Will it include Lumberjack calls?  If so, I'm not super keen because it would add a build time dependency to my package.  I dislike adding dependencies (runtime or buildtime) unless they are truly central to the package (e.g. crayon for this package).  This is especially true now that CRAN requires functions used in tests to be in "suggests" at a minimum.

**Comment by markvanderloo** [comment]
Yes Enhances can only be used as referring mechanism. It does not create a dependency on either side other than the links on CRAN.


I would not include lumberjack calls in the test, but I probably want to do some basic unit tests on small datasets for the logger.

**Comment by markvanderloo** [comment]
Also I'm planning to create a (static) vignette with examples from all the enhancing packages.

**Comment by brodieG** [comment]
Sounds good, go ahead and submit the PR for me to review.  Please do so off of the "development" branch.

**Comment by markvanderloo** [comment]
Will do. Will be a week or so before I get to it.

**Comment by brodieG** [comment]
Ok, no problem, though you might miss the maintenance release I'm prepping now.  Not a big deal though obviously, will go out with the next one.

**Comment by brodieG** [comment]
It appears interest has waned on this.  Feel free to re-open if this is something that becomes important again.
