### ISSUE TITLE
Support R 3.1?

### ISSUE THREAD

**Issue by krlmlr** [brodieG/diffobj#123]
Tried to set up a testing environment for R 3.1 for _fansi_, but noticed that _diffobj_  requires R 3.2. What's the reason?

**Comment by brodieG** [comment]
Ok, I figured out what happened.  Since releasing `fansi`, I added the Depends >= 3.2 to `diffobj`, thinking that was a smart thing to do given that I do not test `diffobj` for <= 3.2...  I'll need to fix that too.

**Comment by krlmlr** [comment]
Thanks! The tidyverse packages aim at supporting R >= 3.1, it's a baseline not too far back in the past.

**Comment by brodieG** [comment]
Yes, I just failed to remember that `fansi` has a suggests dependency on `diffobj`, and as such `diffobj` also needs to be R3.1 like `fansi`.  It was a careless mistake.  I'll address this first and get it on CRAN, and then the `fansi` issues (otherwise tests will keep failing on 3.1).

**Comment by brodieG** [comment]
Fyi, working on this now.  There are a couple of potential issues I need to figure out.  This will be a blocking issue for all the `fansi` issues that need to be resolved.  I hope to get this done in the next couple of days.

**Comment by brodieG** [comment]
This is now fixed on the development branch.  Took longer than I expected as there was a surprising (to me) amount of code that relied on > 3.2.

**Comment by krlmlr** [comment]
Thanks for taking the effort!

**Comment by brodieG** [comment]
Not at all!  When I agreed to make `fansi` 3.1 compatible, I implicitly committed myself to do the same for `diffobj`, even though I didn't quite realize it at the time.
