### ISSUE TITLE
Increasing the width of rendered HTML in Shiny

### ISSUE THREAD

**Issue by eckyu** [brodieG/diffobj#127]
Hi, thanks very much for your help on an earlier issue #125  .  Taking your example for rendering HTML...

`HTML(
        as.character(
          diffPrint(1:3, 2:4, format='html',style=list(html.output='diff.w.style')
) ) )})`

I see that it fills half the width of the output space.  I have tried changing the disp.width parameter but without success.  I am wondering if there are other ways to increase the width so as to display more contents per line of space?  

Thanks very much for your help on this.

**Comment by brodieG** [comment]
Are you sure you are not dealing with a Shiny formatting issue (i.e. it is your shiny page that is making the display narrow)?  Here I have two examples that get as wide as my laptop display:


<img width="1222" alt="screen shot 2018-08-28 at 9 16 24 am" src="https://user-images.githubusercontent.com/6105908/44725442-45120480-aaa3-11e8-8cd1-f98e94323b57.png">

Generated with:

```
library(shiny)
library(diffobj)
shinyApp(
  ui=htmlOutput('diffobj_element'),
  server=function(input, output) {
    output$diffobj_element <- renderUI({
      HTML(
        as.character(
          diffPrint(1:99, 2:100, format='html', disp.width=120,
            style=list(html.output='diff.w.style')
) ) )}) } )
shinyApp(
  ui=htmlOutput('diffobj_element'),
  server=function(input, output) {
    output$diffobj_element <- renderUI({
      HTML(
        as.character(
          diffPrint(
            1:99, 2:100, format='html', disp.width=120,
            mode='unified',
            style=list(html.output='diff.w.style')
) ) )}) } )
```

**Comment by eckyu** [comment]
Thanks very much for replying and for the example.  I have tried your example and can confirm that they do indeed fill up the width of the space.

I see that theres two things causing the render to reduce in width..., for example if I do this...

`library(shiny)
library(diffobj)
shinyApp(
  ui=fluidPage(htmlOutput('diffobj_element')),
  server=function(input, output) {
    output$diffobj_element <- renderUI({
      HTML(
        as.character(
          diffPrint(
            1:97, 2:96, format='html', disp.width=120,
            mode='unified',
            style=list(html.output='diff.w.style')
          ) ) )}) } )`

Where I simply wrap htmlOutput(..) with fluidPage()..., the render halves in width...

![image](https://user-images.githubusercontent.com/32898468/44906805-86770e00-ad48-11e8-87a4-489691cfbad7.png)

But if I remove it...., the render now becomes full width...  

![image](https://user-images.githubusercontent.com/32898468/44906883-c3db9b80-ad48-11e8-923f-d89d1ec6bf73.png)

Presumably it is the shiny settings?  If so, is there a way to overcome this?

Thanks again for your help on this.

**Comment by brodieG** [comment]
There is some unpleasant interaction between the `diffobj` html, and shiny.  Part of it is probably because normally there is some JS that re-adjusts diff widths that is not included when we output with `html.ouput='diff.w.style'`.

I'll look at this when I work on #126, but that will probably not be for a while (months).

In the meantime, you have one more option which is to use the ANSI CSI colored output of `diffPrint`, and then converting it to HTML with `fansi`:

```
library(shiny)
library(diffobj)

options(crayon.enabled=TRUE)
shinyApp(
  ui=fluidPage(htmlOutput('diffobj_element')),
  server=function(input, output) {
    output$diffobj_element <- renderUI({
      diff <- diffPrint(
        1:100, 2:101, disp.width=120, pager='off', format='ansi256',
        brightness='light'
      )
      pre(
        HTML(
          fansi::sgr_to_html(paste0(as.character(diff), collapse="\n"))
)) }) } )
```
<img width="1014" alt="screen shot 2018-08-31 at 10 10 39 am" src="https://user-images.githubusercontent.com/6105908/44917351-252e4b00-ad06-11e8-94df-ed2538651427.png">

This has its own drawbacks, so you will have to chose what you prefer.

Alternatively, you can poke around the CSS and try to figure out what's going wrong.

**Comment by cpsievert** [comment]
The issue boils down to the bootstrap CSS clashing with the css here 

https://github.com/brodieG/diffobj/blob/c46b4d12b63b49e905235c44081fc9f399cd2e00/inst/doc/embed.html#L96

Note that the `row` class has special meaning in bootstrap and 99% of **shiny** app's use bootstrap, so this is a big deal for anyone wanting to leverage **diffobj** in **shiny**
