### ISSUE TITLE
repeated 'pager' entry in prototype for pager class

### ISSUE THREAD

**Issue by BillDunlap** [brodieG/diffobj#132]
In CRAN's diffobj-0.2.2 R/pager.R provides two 'pager' entries in the prototype for class 'Pager'.  That seems wrong and one of them should be omitted.  Currently the second, which calls stop(), is the one used, but it seems like the first would be a better default value.

```
setClass(
  "Pager",
  slots=c(
    pager="function", file.ext="character", threshold="numeric",
    ansi="logical", file.path="character", make.blocking="logical"
  ),
  prototype=list(
    pager=function(x) writeLines(readLines(x)), file.ext="", threshold=0L,
    pager=function(x) stop("Pager object does not specify a paging function."),
    ansi=FALSE, file.path=NA_character_, make.blocking=FALSE
  )
```

**Comment by brodieG** [comment]
Obviously this is an oversight.  Thanks for reporting.  Looking at the blame it appears that I intended the first one to be the new setting, and clearly failed to test for that properly.  I'll add that to the list for the next release.

Is this causing you problems right now?  Next release probably won't be for a while unless you actually have an immediate need for this being fixed.  If so I can prioritize earlier.

**Comment by BillDunlap** [comment]
Thanks.   No hurry, I just was taking another look at the package.

**Comment by brodieG** [comment]
This should be fixed on the `development` branch.  Hope to send out to CRAN in the next week or two.

**Comment by brodieG** [comment]
Up on CRAN now.
