### ISSUE TITLE
diffobj does not install due to temp location check on R 3.6

### ISSUE THREAD

**Issue by andrewrech** [brodieG/diffobj#138]
```
R: install.packages("diffobj")
```
 

> Installing package into ‘/usr/local/lib/R/site-library’
> (as ‘lib’ is unspecified)
> trying URL 'https://cloud.r-project.org/src/contrib/diffobj_0.2.3.tar.gz'
> Content type 'application/x-gzip' length 434192 bytes (424 KB)
> downloaded 424 KB
> * installing *source* package ‘diffobj’ ...
> ** package ‘diffobj’ successfully unpacked and MD5 sums checked
> ** using staged installation
> ** libs
> gcc -fopenmp -I"/usr/share/R/include" -DNDEBUG     -fpic  -g -O3 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c diff.c -o diff.o
> gcc -fopenmp -I"/usr/share/R/include" -DNDEBUG     -fpic  -g -O3 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c diffobj.c -o diffobj.o
> gcc -fopenmp -I"/usr/share/R/include" -DNDEBUG     -fpic  -g -O3 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c init.c -o init.o
> gcc -fopenmp -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o diffobj.so diff.o diffobj.o init.o -L/usr/lib/R/lib -lR
> installing to /usr/local/lib/R/site-library/00LOCK-diffobj/00new/diffobj/libs
> ** R
> ** inst
> ** byte-compile and prepare package for lazy loading
> ** help
> *** installing help indices
> ** building package indices
> ** installing vignettes
> ** testing if installed package can be loaded from temporary location
> 2019/07/04 08:28:20 true
> 2019/07/04 08:28:20 0 1 1
> 2019/07/04 08:28:20 Test 1 {Jeoffry [1 2 3]} 0x584f10 0xc00002a0e0
> Error in slibs[are_shared] : invalid subscript type 'list'
> * removing ‘/usr/local/lib/R/site-library/diffobj

```
$ R CMD INSTALL . --no-staged-install
```

> * installing to library ‘/usr/local/lib/R/site-library’
> * installing *source* package ‘diffobj’ ...
> ** using non-staged installation
> ** libs
> gcc -fopenmp -I"/usr/share/R/include" -DNDEBUG     -fpic  -g -O3 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c diff.c -o diff.o
> gcc -fopenmp -I"/usr/share/R/include" -DNDEBUG     -fpic  -g -O3 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c diffobj.c -o diffobj.o
> gcc -fopenmp -I"/usr/share/R/include" -DNDEBUG     -fpic  -g -O3 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c init.c -o init.o
> gcc -fopenmp -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o diffobj.so diff.o diffobj.o init.o -L/usr/lib/R/lib -lR
> installing to /usr/local/lib/R/site-library/diffobj/libs
> ** R
> ** inst
> ** byte-compile and prepare package for lazy loading
> ** help
> *** installing help indices
> ** building package indices
> ** installing vignettes
> ** testing if installed package can be loaded
> * DONE (diffobj)

```
> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_3.6.0
```

```
Linux yidhra 4.15.0-1040-aws #42-Ubuntu SMP Fri May 17 13:47:10 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by brodieG** [comment]
Thanks for reporting.  Unfortunately I cannot reproduce locally when building from source under the same R version.  Do other packages with compiled code work install fine and it's just `diffobj` that doesn't work?

Additionally, the nature of the error makes me think this is not a `diffobj` issue as the test itself is failing with a clearly unexpected error, and `diffobj` should not be able to cause that to happen.  This recently discussed [r-devel issue seems  related](https://stat.ethz.ch/pipermail/r-devel/2019-May/077855.html).

As you appear to have a work-around, and I think this is probably not a `diffobj` issue, I will tentatively consider this issue resolved.  If you have additional evidence that make you think this is definitely `diffobj` and not the issue discussed in r-devel, please feel free to re-open the issue.

**Comment by andrewrech** [comment]
I have just installed 254 R packages on fresh Linux box, but only diffobj fails. Many obviously contain compiled code. That r-dev issues does seem like it, but I can't explain while only diffobj is failing.

Consider:

https://developer.r-project.org/Blog/public/2019/02/14/staged-install/
https://github.com/kalibera/rstagedinst

I ran `sicheck.R` above on diffobj and its deps, but it found nothing.

Feel free to close.

**Comment by brodieG** [comment]
Hmm, that is odd and concerning.  I'm going to try to run this on Linux to see if I can reproduce.  I do use `system.file`, but at run time so that should not be a problem.

**Comment by andrewrech** [comment]
Yea I use system.file in my own packages that install fine. Sorry, wish I had some insight here.

**Comment by brodieG** [comment]
I tried to reproduce this under rocker/r-ver:3.6.0 and I could not.

**Comment by andrewrech** [comment]
I will try to reproduce on a clean box.

**Comment by brodieG** [comment]
Since I haven't heard back I'm going to assume this has gone away.  Feel free to re-open if you have additional details to provide.
