### ISSUE TITLE
Return ses() output in more computable form?

### ISSUE THREAD

**Issue by hadley** [brodieG/diffobj#143]
i.e.. I'm doing this:

```R
ses <- function(x, y) {
  out <- diffobj::ses(x, y, max.diffs = 100)
  out <- rematch2::re_match(out, paste0(
    "(?:(?<x1>\\d+),)?(?<x2>\\d+)",
    "(?<t>[acd])",
    "(?:(?<y1>\\d+),)?(?<y2>\\d+)"
  ))[1:5]

  out$x1 <- ifelse(out$x1 == "", out$x2, out$x1)
  out$y1 <- ifelse(out$y1 == "", out$y2, out$y1)

  out$x1 <- as.integer(out$x1)
  out$x2 <- as.integer(out$x2)
  out$y1 <- as.integer(out$y1)
  out$y2 <- as.integer(out$y2)

  out
}
```

but I'm sure you could compute that more efficiently at a lower level.

**Comment by brodieG** [comment]
Internally `diffobj::ses` calls `diffobj:::diff_myers` and the returns the raw data (note `?diff_myers` is out of date, I'm realizing):

```
> xx <- diffobj:::diff_myers(letters[1:5], letters[2:6])
> str(xx)
Formal class 'MyersMbaSes' [package "diffobj"] with 6 slots
  ..@ a     : chr [1:5] "a" "b" "c" "d" ...
  ..@ b     : chr [1:5] "b" "c" "d" "e" ...
  ..@ type  : Factor w/ 3 levels "Match","Insert",..: 3 1 2
  ..@ length: int [1:3] 1 4 1
  ..@ offset: int [1:3] 1 2 5
  ..@ diffs : int 2
```

The strings `ses` outputs are produced by the `as.character` method used by `show`.

So short term you can get the data that way.  Longer term I can add a method that returns this.

**Comment by brodieG** [comment]
Also, if you can give me a sense of what time frame this feature would be useful to you (i.e. when is too late to be useful) let me know.  I'm way behind on all sorts of things so absent specific timelines things are likely to sit for a while.

**Comment by hadley** [comment]
I’m already using the function above so there’s no rush. The only advantage would be a small performance boost, but I doubt it’s a bottleneck for me anyway.

**Comment by brodieG** [comment]
Just added `ses_dat` which I think gives you the data in a good format for your pruposes.  This is the example.  It's now in the [development branch](https://github.com/brodieG/diffobj/tree/development).

<img width="496" alt="image" src="https://user-images.githubusercontent.com/6105908/81359914-70d2f380-90a8-11ea-935e-005778a6f605.png">

**Comment by hadley** [comment]
Thanks!
