### ISSUE TITLE
Figure out how to get Rstudio Autocomplete To Read Default Method Docs

### ISSUE THREAD

**Issue by brodieG** [brodieG/diffobj#148]
From #147:

> I got stymied there by relying on argument auto-complete in RStudio -- it only returns options for the default method, so I didn't see the ANY signature arguments to tinker around with.

**Comment by MichaelChirico** [comment]
IINM it's not really something in scope...  I don't think RStudio looks very deeply at the object in the current expression, so the default is usually returned -- here's a `data.table` example to show you it's not just `diffObj`:

<img width="220" alt="Screenshot 2020-06-03 at 3 29 27 AM" src="https://user-images.githubusercontent.com/7606389/83561503-88d45080-a54a-11ea-8a82-b158b90dbc57.png">

Ideally (?) tab would easily be able to say "`iris` is a `data.table`, so `as.data.frame` in this expression will call `as.data.frame.data.table`"

**Comment by brodieG** [comment]
It could also look at the doc file more deeply.  For example, diffPrint documents both the generic and the ANY method in the same page.  It wouldn't be a stretch to use both when providing auto-complete options.

**Comment by MichaelChirico** [comment]
I deleted my earlier comment since it was in error. Actually RStudio does seem to pick up some method docs (I tried `d <- as.IDate(Sys.Date()); as.POSIXct(d, <TAB>`). Maybe it's just for S3?

**Comment by brodieG** [comment]
Possibly an Rstudio bug.  Closing until there is evidence it isn't a bug there.

https://github.com/rstudio/rstudio/issues/7851
