### ISSUE TITLE
How to embed diffobj into PDF / Latex document?

### ISSUE THREAD

**Issue by krzyklo** [brodieG/diffobj#151]
I do not see any info on this important use case in the documentation. I am miss something??

**Comment by brodieG** [comment]
If you can embed HTML in those formats then you should be able to embed diffobjs in there as well.  I have not done it so don't have direct instructions for how to do so.  You can look at the [embedding diffobjs vignette][1] for ideas.  If you succeed in doing this, and you share them with me I can add them to documentation.

[1]: https://cran.r-project.org/web/packages/diffobj/vignettes/embed.html

**Comment by krzyklo** [comment]
Dear briodieG,
Thank you for this beautiful package, that is so useful.. that I abandoned PDF for the time being... (I would use PageDown if need PDF)
At that moment, I just switched to HTML report, to use diffobj, I will try later experiment with **raw_html** in knitr...

**Comment by brodieG** [comment]
Ok, I'll close the issue for now then.  If you figure out how to do it with pdf do re-open and post your methods here.
