### ISSUE TITLE
extract the difference value from diffobj::diffchr

### ISSUE THREAD

**Issue by FarhanShahJahan** [brodieG/diffobj#161]
I there any way for me to extract the difference value and put into new columns in my dataframe

**Comment by brodieG** [comment]
Hi @FarhanShahJahan.  It will help me if you give me an example of exactly what you want.  Could you produce an example with e.g. a one row and one column data frame and what you are hoping to extract exactly?

**Comment by FarhanShahJahan** [comment]
Opps sorry, I wanted to extract the difference value when compared to both column, for example:
col1 <- 'John Smith'
col2 <- 'John Will Smith'
expected output: 'Will'

**Comment by brodieG** [comment]
Got it.  You can use `ses_dat`, although it takes a little processing because `diffobj` naturally does line diffs.  So you need a vector of words, which you can create with `strsplit`:

```
library(diffobj)
col1 <- 'John Smith'
col2 <- 'John Will Smith'

col1a <- unlist(strsplit(col1, " "))
col2a <- unlist(strsplit(col2, " "))
dat <- ses_dat(col1a, col2a)
with(dat, val[op != 'Match'])
## [1] "Will"
with(dat, val[op == 'Match'])
## [1] "John"  "Smith"
```

Does this get to what you want?

**Comment by brodieG** [comment]
@FarhanShahJahan since I have not heard from you I'm going to assume my solution addresses your question.  Feel free to re-open this issue if it doesn't.
