### ISSUE TITLE
problem installing diffobj with R/4.

### ISSUE THREAD

**Issue by zyzhang1992** [brodieG/diffobj#162]
Please note that it installed the dependency crayon successfully and I can also load crayon successfully but I still get the error that  there is no package called 'crayon' For details please see below. 

also installing the dependency 'crayon'

trying URL 'https://cran.microsoft.com/src/contrib/crayon_1.5.0.tar.gz'
Content type 'application/octet-stream' length 40099 bytes (39 KB)
==================================================
downloaded 39 KB

trying URL 'https://cran.microsoft.com/src/contrib/diffobj_0.3.5.tar.gz'
Content type 'application/octet-stream' length 479276 bytes (468 KB)
==================================================
downloaded 468 KB

* installing *source* package 'crayon' ...
** package 'crayon' successfully unpacked and MD5 sums checked
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (crayon)
* installing *source* package 'diffobj' ...
** package 'diffobj' successfully unpacked and MD5 sums checked
** using staged installation
** libs
gcc -I"/share/software/user/open/R/4.1.2/lib64/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c diff.c -o diff.o
gcc -I"/share/software/user/open/R/4.1.2/lib64/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c diffobj.c -o diffobj.o
gcc -I"/share/software/user/open/R/4.1.2/lib64/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c init.c -o init.o
gcc -shared -L/share/software/user/open/R/4.1.2/lib64/R/lib -L/usr/local/lib64 -o diffobj.so diff.o diffobj.o init.o -L/share/software/user/open/R/4.1.2/lib64/R/lib -lR
installing to /home/users/zyzhang/R/x86_64-pc-linux-gnu-library/4.1/00LOCK-diffobj/00new/diffobj/libs
** R
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'crayon'
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package 'diffobj'
* removing '/home/users/zyzhang/R/x86_64-pc-linux-gnu-library/4.1/diffobj'

The downloaded source packages are in
        '/tmp/RtmpHAh76p/downloaded_packages'
Warning message:
In install.packages("diffobj") :
  installation of package 'diffobj' had non-zero exit status

**Comment by brodieG** [comment]
Hi @zyzhang1992.  For some reason the {crayon} installation does not appear to be registering.  I don't think this is a {diffobj} specific issue, but rather something weird is going on with your R package library.  I would try:

```
remove.packages(c('crayon', 'diffobj'))
q()
```

Then restart R and:

```
install.packages('crayon')
if(!require(crayon)) stop("crayon install failed")
install.packages('diffobj')
```

Hopefully this will either work, or at least confirm there is something wrong with the `crayon` installation.

**Comment by brodieG** [comment]
As I have not heard back from you I will assume the issue is resolved.  Feel free to re-open if you're still seeing the problem after trying the debugging steps outlined above, although I do think it is unlikely to be a `diffobj` specific issue.
