### ISSUE TITLE
Use RStudio Viewer Window When Available Instead of Browser

### ISSUE THREAD

**Issue by brodieG** [brodieG/diffobj#51]
As per [Noam Ross](https://twitter.com/noamross/status/760115813559009280).

**Comment by timelyportfolio** [comment]
I'll be happy to help here.  Would it be ok to add `htmltools` dependency?

**Comment by brodieG** [comment]
My initial inclination is to avoid doing so.  The `markdown` dependency is a suggests as opposed to an imports.  I'm not completely opposed, but would want to first believe that doing the integration without `htmltools` is difficult.  In the little research I did it seemed straightforward.

**Comment by brodieG** [comment]
Actually, the basic implementation was super easy.  It's working already.  Need to think about how to handle the inset vs. maximized sizes though since the standard small screen of the viewer is no good with the default width settings.

**Comment by brodieG** [comment]
The [viewer branch](https://github.com/brodieG/diffobj/tree/viewer) goes to the RStudio viewer.  I haven't tested much at all though.
