### ISSUE TITLE
Error when diffing list containing empty list

### ISSUE THREAD

**Issue by wch** [brodieG/diffobj#88]
It's not clear to me whether `diffObj` is meant to be used for complex structures like nested lists, but it seems that at it at least shouldn't give an error (or that the error is more informative). Example:

```
> diffObj(list(list()), list(list()))
Error in trim_sub(obj.as.chr, stripped) : 
  Logic Error: trimmed string is not a substring of orginal, contact maintainer
Error in apply_trim(target, tar.capt.p, etc@trim) : 
  `*trim` method produced an error when attempting to trim ; If you did not define custom `*trim` methods contact maintainer (see `?trim`).
```

**Comment by brodieG** [comment]
This is definitely a bug.  It is supposed to work well with nested structures (see vignette example with `lm` output), but obviously I didn't properly handle the case you bring up.  I'll fix this in the next release (and hopefully get development branch fixed today).  In the meantime, you can use:
```
diffStr(list(list()), list(list()))
```
or
```
diffObj(list(list()), list(list()), trim=FALSE)
```
to work around the issue.  Thanks for reporting.

**Comment by brodieG** [comment]
This should now be working in `install_github('brodieg/diffobj@development')`.  Unfortunately I seem to have introduced some minor regressions for R 3.4.x in the process, but I don't have time to look at those now.  The R release tests all pass.  I am hoping to get version 0.1.6 with these fixes and others out to CRAN in the next week or two.

Let me know if for whatever reason this does not work for you.

Also, feel free to add feature request issues if you have use cases for `diffobj` that don't appear currently covered.
